package: yform_rapidmail
version: 1.0.2
author: alex+ Digitales Marketing
supportpage: https://github.com/alexplusde/yform_rapidmail/

requires:
    redaxo: '^5.15'
    ycom: '^4.2.1'

default_config:
    api_user_hash: ''
    api_password_hash: ''

page:
    hidden: true

pages:
    yform/rapidmail:
        title: 'Rapidmail'
        icon: rex-icon  fa-paper-plane
        perm: yform_rapidmail[]
        
    yform/rapidmail/settings:
        title: 'Einstellungen'
        icon: rex-icon fa-cogs
        perm: yform_rapidmail[]

    yform/rapidmail/docs:
        title: 'Docs'
        icon: rex-icon fa-book
        perm: yform_rapidmail[]
